### ISSUE TITLE
.md file was rendered incorrectly

### ISSUE THREAD

**Issue by Amaindex** [hzlmn/diy-async-web-framework#7]
https://github.com/hzlmn/diy-async-web-framework/blob/a4b89f712d0ee55d41845eaffbee0a6092e84a31/.gitattributes#L2
This line of code seems to have a new side effect. 
The following files cannot be rendered correctly in markdown format:
https://github.com/hzlmn/diy-async-web-framework/blob/master/README.md
https://github.com/hzlmn/diy-async-web-framework/blob/master/README_CN.md

**Comment by hzlmn** [comment]
Hi! Good catch thanks and sorry for terribly long delay.  Fixed attributes.
